### ISSUE TITLE
[RFC] Split DKP from package

### ISSUE THREAD

**Issue by Sajaki** [bbDKP/bbGuild#263]
As bbdkp is becoming an extension, the original scope has become too big to fit within the extension concept. 

Increasingly, people want just a guild community tool, and the dragon kill points is becoming secondary, features that are becoming more important are roster integration, calendar integration, guild news rss. 

Therefore the core should be focussing on Guilds first. The extension name should then reflect this and be renamed "bbGuild". 

All DKP related features will then be implemented in a side extension. this also fits with the RFC to replace the dkp & adjustment table with a transaction based model (#173).

**Comment by Gjeep** [comment]
Excellent news. I think its a great move.
It shows you are very in touch with your users. :+1: 

I would also suggest supporting existing portals with blocks instead of writing your own.

Best regards :)

**Comment by sgtevmckay** [comment]
Understood...and seems an intelligent plan that is much needed... I must admit that I am interested in everything, but the DKP. so I am among those that you have considered. Especially as our guild Instance Groups have developed our own loot distribution that we are very satisfied with :D

Gjeep:
I understand your position, but I imagine that this would be creating a fresh series of extensions based on each available portal, and may be more trouble than we realize. Unless teh framework of each extension can be made to simply add Blocks to current extensions. I do not think this will be possible (???)

I ask your patients in this to see what Sajaki comes up with for the Forums portal, and its abilities, I believe that although this would create a situation where you will have to abandon the portal you currently use, but I believe that you will be most satisfied by the end result.

The only thing that I utilize, that I believe Sajaki's portal does not support is an ability to add open HTML codes, so that we may then add custom fields in a custom block.

If this is true, May I ask of you Sajaki to look into adding this "block" to your portal build.
2 other current portals do have this ability.

Thank you both

**Comment by sgtevmckay** [comment]
Sajaki....Please advise when we can starting testing.
I have a sandbox PhP forum specifically for testing extensions and doing custom Style builds

Than you sir.

**Comment by Gjeep** [comment]
@sgtevmckay thats precisely the idea. Current validated portal extensions support blocks, and a lot of other features. It would be way out of the scope of bbdkp to support all the different needs for portals. Instead he could choose to make blocks available for each of the moduels, which would free up time, instead of having to trouble shoot and maintain his own separate portal.

But I'm fine either way, it was just a suggestion. :)

**Comment by sgtevmckay** [comment]
Wholly understood :D

**Comment by Sajaki** [comment]
I get your point, but not sure yet if i'll drop the portal part.

**Comment by sgtevmckay** [comment]
If ay do drop the portal part, then I would definitely appreciate the modules for the current Portals, 
Especially for Board 3 Portal....I think them to be recently approved.

But either way, you been busting your arse, and I do appreciate you....so I will be grateful for how ever you decide to proceed <3

Testing starts on Monday (Tomorrow???), just got Wife aggroed ;)
