### ISSUE TITLE
Conversion from MOD to Extension

### ISSUE THREAD

**Issue by Sajaki** [bbDKP/bbGuild#98]
1.x series will remain a MODX for phpBB 3.0.x, will be maintained for the remaining pbpBB 3.0 lifespan. 

2.0 will an extension for phpbb 3.1 exclusively.

**Comment by sgtevmckay** [comment]
Greetings:

Many are awaiting Patiently for this, and the other addons,  most beloved Mod to become an Extensions.
Although many are heartbroken, wondering if you have abandoned bbDKP.

I hope I am not out of line, but I feel I need to mention that Blizzard is moving to a regulated API.
The current API is being phased out, in favor of the following:
http://us.battle.net/en/forum/topic/13815891462

Full API forum here:
http://us.battle.net/en/forum/15051532/

Because of the new API regulations, Future Extensions will need to have teh forum Aministartors register for an API Key.
Such as in this Extension:
https://github.com/AJH16/PHPBB-BattleNet-OAuth

I would suggest that thsi should not be an issues, except for the code replacements in bbDKP 1.x
And the new necessary fields in ACP to enter teh API Key


I notice that activity has been very slim here, but do you have any kind of time line for release of bbDKP Extensions.

I am sorry to bother you, and hope that I have been of some assistance.

**Comment by AJH16** [comment]
OK, you just made my day. That phpbb oauth extension you linked is mine. That said, you don't need to use the oAuth authentication for the mod, but you do need an api key for advanced functionality beyond the armory xml back end. 
It really isn't particularly hard to swap between though. I even have my local copy of bbdkp pulling some information from my new api integration. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by sgtevmckay** [comment]
I do not know how to properly express my excitement on hearing from you.
Thank you.

Please read following when you are at your system....may be too much to read on phone ;)

Our server services blew up several months ago, and we went ahead and migrated to 3.1.3 (now to .4) and are heartbroken that we lost bbDKP and its modules, unfortunately our service provider will not allow us to migrate back to PhPbb 3.0.x, this would violate their ToS. So I have been desperately looking for replacement extensions for several months now.

To that end I may have just stepped on your toes, so I hope this will not be embarrassing to you :/
I just made a post to the Blizz API forums. Please read at your leisure....If you wish, I will delete the post.
http://us.battle.net/en/forum/topic/17605632588

Just hearing from you is enough to know that this is not dead.

Thank you again.

**Comment by AJH16** [comment]
Sadly, I don't have the time to tackle something as big as bbDKP right now.  My specialization is more on the voice and security integration.  I actually don't even use bbDKP for it's main function.  I just use it as a data puller to sync between the game, Teamspeak 3 and my forum.  I don't know much about the level of sajaki's involvement.  I do know that phpbb extensions themselves are kind of a pain as I learned from the oAuth one.

**Comment by sgtevmckay** [comment]
Having retired years ago from the days of BASIC and FORTRAN, I understand. I have been away from programming for so long, it is almost a foreign language to me now :(

So I will hold out faith for a port on bbDKP, and its Modules. As I have taken the step of adding it to the Blizz API Community as well.

Thanks again for your contribution to the PhPBB Community, I have been passing on the Extension to other forum Admin in the WoW Community.

**Comment by Gjeep** [comment]
Its a real shame if this does not get ported. I have been a fan a long time. :)
I mainly used the apply and calendar functions.

**Comment by sgtevmckay** [comment]
Indeed....especially now that these are exciting times with the new Blizz API, and the ability to work more closely with the blizzard folks. Especially if there are requests to consider for blizz to open additional facilities.

I would very much like to see w full iteration of these on the new forums, and find out what else Sajaki could potentially come up with

**Comment by AJH16** [comment]
One other thought would be to approach the bbwow team and see if they have any interest in the project if Sajaki actually has abandoned it. It would enable tighter integration if they are up for it.   
I'd also be able to provide some assistance to the effort, I just don't have the time to do it all myself, but I could probably help out some if someone with more phpbb modding experience broke it up in to smaller pieces. 
I also am horribly fail at ui work. I'm entirely a back end guy. 
Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by sgtevmckay** [comment]
Thanks for the great suggestions :D
Since i am on a roll, I may as well present this to PayBas.
I have actually been a bit hesitant as PayBas seems to be terribly busy.
But, Nothing ventured nothing gain.

**Comment by sgtevmckay** [comment]
It has been almost 2 months, of which I have heard nothing from anyone that I have contacted.
It is unfortunate that such a brilliant and needed piece of software now appears dead, and with no interest by anyone that I have contacted in taking over.
Either because they are worried about stepping on Sajaki's toes, or a plethora of other excuses.

Most Unfortunate.
I will not be expending any further time of this lost pipe dream :/

**Comment by sgtevmckay** [comment]
???

**Comment by Sajaki** [comment]
it's alive again.

**Comment by sgtevmckay** [comment]
Thank you.....
Looking forward to helping as I can.

Be advised: Your project was just now listed as abandoned at the PHPBB forums.
https://www.phpbb.com/community/viewtopic.php?p=14283786#p14283786

**Comment by Gjeep** [comment]
Yay! :+1:

**Comment by AJH16** [comment]
You forgot to cackle maniacally like Frankenstein...


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by sgtevmckay** [comment]
Nah....I didn't at all overlook the Cackle and the screams of "Its Alive!.......AAAAAAAALLLLLLLLIIIIIVVVVVEEEEE!!!" Mmwmwmwmwwhwhahhahahaaaaa

I am just trying to be patient and contain myself ;)

**Comment by Sajaki** [comment]
it's installable at this point. 
still needs to be done : front end and some ajax js in acp,

**Comment by sgtevmckay** [comment]
Very good, and thanks for the notice.
Timing is excellent as I just installed a fresh Sandbox on home server with new Prosilver compliant Style from PhPBB.de

This is going to be fun
